
services:
  postgres:
    container_name: postgres
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: clinique
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $(cat /run/secrets/db_user) -d postgres" ]
      timeout: 20s
      retries: 5

volumes:
  postgres_data:
