
###

//Authentication 1

POST  http://localhost:8080/api/v1/auth
Content-Type: application/json

{
  "email": "alphadiobiya@gmail.com",
  "password": "123456789"
}


###

//Authentication 2

POST  http://localhost:8080/api/v1/auth
Content-Type: application/json

{
  "email": "diallo.habibatou2710@gmail.com",
  "password": "123456789"
}

###
// Get users

GET  http://localhost:8080/api/v1/utilisateurs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbHBoYWRpb2JpeWFAZ21haWwuY29tIiwiZXhwIjoxNzU4NDA3MzQ1LCJpYXQiOjE3NTg0MDU1NDUsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiJ9.OMs6KYkcJqsT76DZZkCqQcBMkfUTz9TWeMnvJDG3sFM

###
// Get users by id

GET  http://localhost:8080/api/v1/utilisateurs/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbHBoYWRpb2JpeWFAZ21haWwuY29tIiwiZXhwIjoxNzU4NDA3MzQ1LCJpYXQiOjE3NTg0MDU1NDUsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiJ9.OMs6KYkcJqsT76DZZkCqQcBMkfUTz9TWeMnvJDG3sFM


###

//inscription 1

POST  http://localhost:8080/api/v1/utilisateurs
Content-Type: application/json

{
  "email": "alphadiobiya@gmail.com",
  "password": "123456789"
}

###

//inscription 2

POST  http://localhost:8080/api/v1/utilisateurs
Content-Type: application/json

{
"email": "diallo.habibatou2710@gmail.com",
"password": "123456789"
}


###

//Enable user

PATCH http://localhost:8080/api/v1/utilisateurs/enable
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbHBoYWRpb2JpeWFAZ21haWwuY29tIiwiZXhwIjoxNzU4NDExOTE5LCJpYXQiOjE3NTg0MTAxMTksInJvbGVzIjpbIlJPTEVfQURNSU4iXX0.QSPaN8btg1OpXCbjLJSUEDkJb8PJGjxmjLwuPx5wAIs

2



