
###

//Authentication 1

POST  http://localhost:8080/api/v1/auth
Content-Type: application/json

{
  "email": "alphadiobiya@gmail.com",
  "password": "Alphadjo30901!"
}

###

//Authentication 2

POST  http://localhost:8080/api/v1/auth
Content-Type: application/json

{
  "email": "diallo.habibatou2710@gmail.com",
  "password": "123456789"
}

###
// Get users

GET  http://localhost:8080/api/v1/utilisateurs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbHBoYWRpb2JpeWFAZ21haWwuY29tIiwiZXhwIjoxNzU5NzczMjcyLCJpYXQiOjE3NTk3NzE0NzIsInJvbGVzIjpbIlJPTEVfUEFUSUVOVCJdfQ.2Dm9SHpu77Mp1XsiBvAutT_Il6ZnGLMGi7KtyFPzUl4

###
// Get users by id

GET  http://localhost:8080/api/v1/utilisateurs/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbHBoYWRpb2JpeWFAZ21haWwuY29tIiwiZXhwIjoxNzU5NzczMjcyLCJpYXQiOjE3NTk3NzE0NzIsInJvbGVzIjpbIlJPTEVfUEFUSUVOVCJdfQ.2Dm9SHpu77Mp1XsiBvAutT_Il6ZnGLMGi7KtyFPzUl4

###

//inscription 1

POST  http://localhost:8080/api/v1/utilisateurs
Content-Type: application/json

{
  "email": "alphadiobiya@gmail.com",
  "password": "Alphadjo30901@"
}

###
//inscription 2

POST  http://localhost:8080/api/v1/utilisateurs
Content-Type: application/json

{
  "email": "diallo.habibatou2710@gmail.com",
  "password": "Alphadjo30901@"
}

###

//Enable user

PATCH http://localhost:8080/api/v1/utilisateurs/enable
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbHBoYWRpb2JpeWFAZ21haWwuY29tIiwiZXhwIjoxNzU4NDExOTE5LCJpYXQiOjE3NTg0MTAxMTksInJvbGVzIjpbIlJPTEVfQURNSU4iXX0.QSPaN8btg1OpXCbjLJSUEDkJb8PJGjxmjLwuPx5wAIs

###

// account acviation by user

PATCH http://localhost:8080/api/v1/utilisateurs/activation
Content-Type: application/json

{
    "code": "447900"
}

###

// password

PATCH http://localhost:8080/api/v1/utilisateurs/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbHBoYWRpb2JpeWFAZ21haWwuY29tIiwiZXhwIjoxNzYxNDg4OTEyLCJpYXQiOjE3NjE0ODcxMTIsInJvbGVzIjpbIlJPTEVfTUVERUNJTiJdfQ._QlIoEFPK6iBN-gAtpeaa371yG9UFKVrjFFTOfjGVqs

{
  "oldPassword": "Alphadjo30901@",
  "newPassword": "Alphadjo30901!"
}

